name: loja_free_style
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  change_app_package_name: ^1.5.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_storage: ^12.4.6
  firebase_core: ^3.13.1
  provider: ^6.1.5
  flutter_staggered_grid_view: ^0.7.0
  transparent_image: ^2.0.1
  faker: ^2.2.0
  azlistview: ^2.0.0
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logoDetona.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logoDetona.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Playwrite
      fonts:
        - asset: assets/fonts/PlaywritePL-Regular.ttf
