// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-3_qDn3LFoM7-atBycvtHeWk22UU8GH0',
    appId: '1:185557586037:web:23a505e8e45ba3f4f5683c',
    messagingSenderId: '185557586037',
    projectId: 'loja-freestyle',
    authDomain: 'loja-freestyle.firebaseapp.com',
    storageBucket: 'loja-freestyle.firebasestorage.app',
    measurementId: 'G-4S0YS0CQL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQACTR2jYjVWfvKXDxlyhNgtPH7TDa5S4',
    appId: '1:185557586037:android:612fc0ac1a1fec34f5683c',
    messagingSenderId: '185557586037',
    projectId: 'loja-freestyle',
    storageBucket: 'loja-freestyle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKSJhT0peJVUg7sWMzvuu8oeOV3YfVsLM',
    appId: '1:185557586037:ios:250e70628af0cf79f5683c',
    messagingSenderId: '185557586037',
    projectId: 'loja-freestyle',
    storageBucket: 'loja-freestyle.firebasestorage.app',
    iosBundleId: 'com.grfulltec.freeStyleApp',
  );

}